services:
  minio:
    extends:
      file: ./minio/compose.yaml
      service: minio
  mongodb:
    extends:
      file: ./mongodb/compose.yaml
      service: mongodb
  mysql:
    extends:
      file: ./mysql/compose.yaml
      service: mysql
  phpmyadmin:
    extends:
      file: ./mysql/compose.yaml
      service: phpmyadmin
  postgresql:
    extends:
      file: ./postgresql/compose.yaml
      service: postgresql
