services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      TZ: ${TZ:-UTC}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-mysql}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-${MYSQL_USER}}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - "./data:/var/lib/mysql"
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      TZ: ${TZ:-UTC}
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER:-mysql}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-mysql}}
    restart: unless-stopped
    ports:
      - 127.0.0.1:8000:80
